/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.family.tree.resources;

import org.springframework.http.ResponseEntity;
import org.springframework.security.access.annotation.Secured;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "com.rfidcollect.codegen.v3.generators.java.SpringCodegen", date = "2019-06-06T16:11:15.514Z[GMT]")
@RequestMapping(value="/api")
public interface PingApi {

    @Secured({"ROLE_ADMIN"})
    @RequestMapping(value = "/ping",
        method = RequestMethod.GET)
    ResponseEntity<Void> pingGet();

}
