/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.family.tree.resources;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.security.access.annotation.Secured;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.family.tree.model.User;

public interface UsersApi {

	@RequestMapping(value = "/users", consumes = { "application/json" }, method = RequestMethod.POST)
	@Secured(value = { "ROLE_ADMIN" })
	ResponseEntity<Map<String, Object>> usersPost(@RequestBody Map<String, Object> body, HttpServletRequest request);

	@RequestMapping(value = "/forgotPassword", consumes = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<Map<String, Object>> usersForgotPasswordPost(@RequestBody Map<String, Object> body,
			HttpServletRequest request);

	@RequestMapping(value = "/resetPassword", consumes = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<Map<String, Object>> usersResetPasswordPost(@RequestBody Map<String, Object> body,
			HttpServletRequest request);

	@RequestMapping(value = "/users/{userId}", method = RequestMethod.DELETE)
	@Secured(value = { "ROLE_ADMIN" })
	ResponseEntity<Void> usersUserIdDelete(@PathVariable("userId") Long userId, HttpServletRequest request);

	@RequestMapping(value = "/users/{userId}", consumes = { "application/json" }, method = RequestMethod.PUT)
	@Secured(value = { "ROLE_ADMIN" })
	ResponseEntity<Map<String, Object>> usersUserIdPut(@PathVariable("userId") Long userId,
			@RequestBody Map<String, Object> body, HttpServletRequest request);

}
